# Generated by Django 5.0.4 on 2024-05-09 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmt", "0004_networkcenter"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampusBuildings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_campus", models.IntegerField()),
                ("nom", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ConferenceCenterBuildings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_conf", models.IntegerField()),
                ("nom", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="DataCenterBuildings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_data", models.IntegerField()),
                ("nom", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("floor_name", models.CharField(max_length=255)),
                ("floor_level", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Equipement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("ip", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("building", models.IntegerField()),
                (
                    "network_center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="nmt.networkcenter",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="nmt.floor"
                    ),
                ),
            ],
        ),
    ]
