# Generated by Django 5.0.4 on 2024-05-19 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nmt", "0005_campusbuildings_conferencecenterbuildings_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CampusBuildings",
        ),
        migrations.DeleteModel(
            name="ConferenceCenterBuildings",
        ),
        migrations.DeleteModel(
            name="DataCenterBuildings",
        ),
    ]
