# Generated by Django 5.0.4 on 2024-05-19 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmt", "0006_delete_campusbuildings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_network_center", models.IntegerField()),
                ("building_name", models.CharField(max_length=255)),
                ("info", models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
