# Generated by Django 5.0.4 on 2024-05-20 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("nmt", "0007_building"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipement",
            name="floor",
        ),
        migrations.RemoveField(
            model_name="equipement",
            name="network_center",
        ),
        migrations.DeleteModel(
            name="Floor",
        ),
        migrations.DeleteModel(
            name="Equipement",
        ),
    ]
