# Generated by Django 5.0.4 on 2024-05-20 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmt", "0008_remove_equipement_floor_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_network_center", models.IntegerField()),
                ("id_building", models.IntegerField()),
                ("nom", models.CharField(max_length=30)),
                ("floor", models.IntegerField()),
                ("info", models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
