# Generated by Django 5.0.4 on 2024-05-20 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmt", "0009_floor"),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_network_center", models.IntegerField()),
                ("id_building", models.IntegerField()),
                ("id_floor_salle", models.IntegerField()),
                ("nom", models.CharField(max_length=30)),
                ("info", models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
