# Generated by Django 5.0.4 on 2024-05-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmt", "0010_local"),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipement",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("id_network_center", models.IntegerField()),
                ("id_building", models.IntegerField()),
                ("id_floor_salle", models.IntegerField()),
                ("id_local", models.IntegerField()),
                ("nom", models.CharField(max_length=30)),
                ("ip", models.CharField(max_length=20)),
                ("model", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=255)),
                ("info", models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
