# Generated by Django 5.0.4 on 2024-05-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nmt", "0011_equipement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Commands",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("command_name", models.CharField(max_length=500)),
            ],
        ),
    ]
